api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
# from geo.cities.views import CityViewset,CityTypeaheadViewset
from geo.places.views import PlacesViewset
from geo.location.views import LocationViewset
from geo.organization.views import OrganizationViewset
from tbnews.views import NewsItemViewset
import geo.location

router = routers.DefaultRouter()
# api = router.SimpleRouter()

router.register(r'locations', geo.location.views.LocationViewset, base_name="locations")
# router.register(r'cities', CityViewset)
router.register(r'places', PlacesViewset)
# router.register(r'cities-typeahead', CityTypeaheadViewset)
router.register(r'organizations', OrganizationViewset)

router.register(r'news', NewsItemViewset)

urlpatterns = patterns('',
                       # Examples:
                       url(r'^v1/', include(router.urls)),
                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

geo/location/urls.py
from django.conf.urls import patterns, include, url
from views import LocationList, LocationCreate, LocationDetail, LocationUpdate

urlpatterns = patterns('geo.location.views',
   # url(r'^add/?$', 'addlocation', name='addlocation'),
   # url(r'^add/?$', LocationCreate.as_view(), name='addlocation'),
   url(r'^add/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/?$', LocationCreate.as_view(), name='addlocation'),
   url(r'^list/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/?$', LocationList.as_view(), name='location_list'),
   url(r'^detail/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/(?P<location>[\w-]+)/?$', LocationDetail.as_view(), name='location_detail'),
   url(r'^edit/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/(?P<location>[\w-]+)/?$', LocationUpdate.as_view(), name='location_update'),
)

geo/location/models.py
from django.contrib.gis.db import models
from geo.places.models import Place
import json as JSON
from django.contrib.gis.geos import GEOSGeometry
# from geo.organization.models import Organization
from django.core.urlresolvers import reverse
from partner.models import Partner

from ideation.idea.models import Idea
from django.contrib.contenttypes import generic
from thoughtbubble.utils import url_safe
from autoslug import AutoSlugField
from tbnews.models import NewsItem

MAKI_CHOICES = (
    ('garden', 'Garden'),
    ('rocket', 'Rocket'),
    ('art-gallery', 'Art Gallery'),
    ('shop', 'shop'),
    ('fast-food', 'Fast Food'),
    ('bar', 'Bar'),
    ('grocery', 'Grocery'),
    ('cinema', 'Cinema'),
    ('baseball', 'Baseball'),
)
class LocationType(models.Model):
    name = models.CharField(max_length=255)
    maki_class = models.CharField(max_length=40, choices=MAKI_CHOICES, default="rocket")

    def __unicode__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name', unique_with='organization')
    address = models.CharField(max_length=255, null=True, blank=True)
    city_and_state = models.CharField(max_length=255, null=True, blank=True)
    zip = models.CharField(max_length=15, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    about = models.TextField(null=True, blank=True)
    sherlock_description = models.TextField(null=True, blank=True)

    what_kind = models.ForeignKey(LocationType, null=True, blank=True)

    geom = models.PointField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    organization = models.ForeignKey('organization.Organization', null=True, blank=True)

    partners = models.ManyToManyField(Partner, null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    some_ideas = generic.GenericRelation(Idea)

    order = models.IntegerField(default=0, blank=True)

    class Meta:
        ordering=['order']


    def __unicode__(self):
        try:
            if self.what_kind and self.what_kind.name == 'organization':
                return "%s" % (self.name)
            return "%s in %s" % (self.name,self.organization.title,)
        except:
            return "%s [no organization]" % (self.name,)

    def get_absolute_url(self):
        # state = 'oh'
        # city = 'columbus'
        # if self.organization:
        #     state = self.organization.neighborhood.state
        #     city = self.organization.neighborhood.city

        return reverse('location_detail',  args=[
            url_safe(self.organization.place.slug),
            url_safe(self.organization.slug),
            url_safe(self.slug)
        ])


    def get_name(self):
        return self.name

    def get_id(self):
        return self.name.lower().replace(' ','-')

    def get_explore_link(self):
        if self.organization:
            return reverse('sherlock', args=[url_safe(self.organization.place.slug), url_safe(self.organization.slug)])

    def get_api_detail_url(self):
        if self.organization.place:
            return reverse('locations-detail', args=[
                url_safe(self.organization.place.slug),
                url_safe(self.organization.slug),
                url_safe(self.slug)
            ])

    def get_api_detail_url(self):
        if self.organization.place:
            return reverse('location_update', args=[
                url_safe(self.organization.place.slug),
                url_safe(self.organization.slug),
                url_safe(self.slug)
            ])

    def add_idea_url(self):
        if self.organization.place:
            return reverse('addidea', args=[
                                            url_safe(self.organization.place.slug),
                                            url_safe(self.organization.slug),
                                            url_safe(self.slug)
            ])

    def list_ideas_url(self):
        if self.organization.place:
            return reverse('idea_list', args=[url_safe(self.organization.place.slug),
                                              url_safe(self.organization.slug),
                                              url_safe(self.slug)
            ])

    def get_update_url(self):
        if self.organization.place:
            return reverse('location_update', args=[url_safe(self.organization.place.slug),
                                              url_safe(self.organization.slug),
                                              url_safe(self.slug)
           ])

    def get_description(self):
        return self.sherlock_description or 'no exploring descripton'

    def save(self, *args, **kwargs):
        # if not self.geom:
        self.geom = GEOSGeometry('POINT(%s %s)' % (self.longitude, self.latitude,))
        if self.geom:
            self.latitude = self.geom[1]
            self.longitude = self.geom[0]

        # Put in the correct Organization
        # s = Neighborhood.objects.filter(geom__contains=self.geom)
        # if s:
        #     self.organization = s[0]


        super(Location, self).save(*args, **kwargs)

    def get_geojson(self):
        return self.geom.geojson

    def get_geometry(self):
        return JSON.loads(self.geom.geojson)

    def get_feature(self):
        return 'Feature'

    def get_properties(self):
        properties = {}
        properties['title'] = self.name
        # properties['marker-size'] = 'medium'
        # properties['marker-color'] = '#f0a'
        # properties['marker-symbol'] = self.what_kind.maki_class if self.what_kind else 'Z'
        properties['link'] = self.get_absolute_url()

        properties['about'] = self.about

        properties['icon'] = {
            "iconUrl": "/static/images/large-featured-location.png",
            "iconSize": [47, 60],
            "iconAnchor": [30, 44],
            "popupAnchor": [0, -25]
        }

        properties['highlight'] = {
            "iconUrl": "/static/images/large-featured-location-hover.png",
            "iconSize": [47, 60],
            "iconAnchor": [30, 44],
            "popupAnchor": [0, -25]
        }

        # properties['icon'] = {
        #     "iconUrl": "http://placekitten.com/50/50",
        #     "iconSize": [50, 50], # size of the icon
        #     "iconAnchor": [25, 25], # point of the icon which will correspond to marker's location
        #      "popupAnchor": [0, -25]  # point from which the popup should open relative to the iconAnchor
        # }
        return properties


    def get_properties_json(self):
        return JSON.dumps(self.get_properties())

    def get_longitude(self):
        return self.longitude

    def get_latitude(self):
        return self.latitude

    def get_fb_sharing(self):
        return {
            'share_copy': "See what's happening at %s and join the conversation!" % (self.name),
            'share_image': 'http://thoughtbubble.us/static/images/TB_socialicon.png',
            'share_caption': 'thoughtbubble.us',
            'share_name': "%s" % self.name,
            'share_link': 'http://thoughtbubble.us' + self.get_absolute_url(),
            }

    def get_linkedin_sharing(self):
        return {
            'summary': "See what's happening at %s and join the conversation!" % (self.name),
            'title': "%s" % self.name,
            'share_link': 'http://thoughtbubble.us' + self.get_absolute_url(),
            }

    def get_twit_sharing(self):
        return {
            'text': "See what's happening at %s and join the conversation! %s" % (self.name, 'http://thoughtbubble.us' + self.get_absolute_url())
        }

    def get_add_news_url(self):
        return reverse('add_news_item', args=['loc',self.id])

    def get_list_news_url(self):
        return reverse('list_news_items', args=['loc',self.id])

    def get_news_items(self):
        return NewsItem.objects.filter(content_type__name='location', object_id=self.id)

    @property
    def get_mapbox_json(self):
        mapbox = {}
        geometry = JSON.loads(self.get_geojson())
        mapbox['type'] = 'Feature'
        mapbox['geometry'] = geometry
        return mapbox


    def get_pictures(self):
        pics = [None,None,None,None]
        for i in range(len(pics)):
            idx = i + 1
            try:
                pics[i] = self.locationimage_set.get(ordering=idx, active=True)
            except:
                pass
        return pics



class LocationNews(models.Model):
    location = models.ForeignKey(Location)
    name = models.CharField(max_length=255, null=True, blank=True)
    img = models.ImageField(upload_to="news", null=True, blank=True)
    content = models.TextField(null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Location News"


def location_image_upload_to(instance, filename):
    prefix = 'locations/%s/%s/%s' % (
                        instance.location.organization.place.id,
                        instance.location.organization.id,
                        instance.location.id,
    )
    return "%s/%s" % (prefix, filename)

class LocationImage(models.Model):
    location = models.ForeignKey(Location)
    img = models.ImageField(upload_to=location_image_upload_to)
    name = models.CharField(max_length=255, blank=True, null=True)
    ordering = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name or "Image %d for %s" % (self.id, self.location,)

geo/location/templates/location/location_detail.html
{% extends 'base.html' %}
{% load classnames %}
{% load getdict %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block title %}
    {{ location.name }}
{% endblock %}

{% block head %}
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.css' rel='stylesheet' />
    <!--[if lte IE 8]>
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.ie.css' rel='stylesheet' />
  <![endif]-->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.min.css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/chosen.jquery.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/location/detail.css" />
{% endblock %}

{% block bodyid %}location-detail{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}
<div id="page-wrapper">
{#    {% if request.user in organization.curators.all or request.user.is_superuser %}#}
{#        <h1 style="margin:0px;"><a href="{{ location.get_update_url }}">admin</a></h1>#}
{#    {% endif %}#}

    <div class="row title">
        <div id="header">
            {{ location.name }}
        </div>
    </div>

        <div class="about">{{ location.about|linebreaks }}</div>
    {% with fb=location.get_fb_sharing twit=location.get_twit_sharing linkedin=location.get_linkedin_sharing %}
        {% include "widgets/sharing.html" %}
    {% endwith %}
        <div class="">
            <div id="map"></div>
        </div>

    <div id="location-stuff">
        <a href="{{ location.get_explore_link }}" class="orange s-button">explore</a>
        <a href="{{ location.add_idea_url }}" class="orange s-button login-required">add</a>
    </div>


    {#    News #}
    {% if news %}
    <div id="news">
        <div class="small-heading">news</div>

        {% include 'widgets/news_feed.html' %}

        <a href="#" class="orange"></a>
    </div>
    {% endif %}

    {#    Pictures #}
    {% if location.get_pictures %}
        <div class="picture-label small-heading">pictures</div>
        <div id="pictures">
            {% for picture in location.get_pictures %}
                <div>
                    <a class="image-popup-no-margins" href="{{ picture.img.url }}">
                        <img src="{% thumbnail picture.img 120x90 %}" alt=""/>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {#    Partners #}
{#    {% if partners %}#}
{#        <div class="large-12 columns small-heading">partners</div>#}
{#        <div id="partners">#}
{#            {% for partner in partners %}#}
{#                {% if partner.link %}#}
{#                    <a href="{{ partner.link }}">#}
{#                  {% endif %}#}
{#                    <img src="{% thumbnail partner.img 200x200 %}" alt=""/></a>#}
{#                {% if partner.link %}#}
{#                    </a>#}
{#                {% endif %}#}
{#            {% endfor %}#}
{#        </div>#}
{#    {% endif %}#}
{#    </div>#}

{#    Ideas #}

    {% include 'idea/idea_filter.html' %}

    {% for idea in ideas %}
            {% include 'idea/idea_for_list.html' %}
    {% endfor %}
{% endblock %}

{% block footerscripts %}
    <script src='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.js'></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-mapbox.js"></script>
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-location.js"></script>#}
{#    {% if organization %}#}

    <script type="text/javascript">


        $(document).ready(function() {
            var map = TB.Map.get_map();
            TB.Map.featureLayer.on('layeradd', function(e) {

                var marker = e.layer,
                        feature = marker.feature;

                marker.setIcon(L.icon(feature.properties.icon));


                // http://leafletjs.com/reference.html#popup
{#                marker.bindPopup(popupContent,{#}
{#                    closeButton: false#}
{#                });#}
            });

            map.setView([{{ location.get_latitude }},{{ location.get_longitude }}],15);

            var map_features = {
                // this feature is in the GeoJSON format: see geojson.org
                // for the full specification
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    // coordinates here are in longitude, latitude order because
                    // x, y is the standard for GeoJSON and many formats
                    coordinates: [{{ location.get_longitude }}, {{ location.get_latitude }}]
                },
                properties: {{ location.get_properties_json|safe }}
            }

            TB.Map.featureLayer.setGeoJSON(map_features);
{#            map.markerLayer.setGeoJSON();#}

        });



    </script>
{% endblock %}

geo/location/templates/location/location_form.html
{% extends 'base.html' %}
{% load classnames %}
{% load getdict %}
{% load widget_tweaks %}

{% block title %}
    {{ dowhat }} a Feature
{% endblock %}

{% block head %}
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.css' rel='stylesheet' />
    <!--[if lte IE 8]>
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.ie.css' rel='stylesheet' />
  <![endif]-->
    <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/leaflet/leaflet.draw.css"/>#}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/tb-addfeature.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/location/location-admin.css" />
{% endblock %}

{% block bodyid %}location-form{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}
    <div id="form-wrapper">
        <form enctype="multipart/form-data" action="{{ action_url }}" method="POST">
            {% csrf_token %}
                    {{ form.errors }}

            <div class="right-side">
                <div id="map"></div>
                <div id="latitude">
                    <label id="lat_label" class="copy" for="{{ form.latitude.auto_id }}">latitude</label>
                    {{ form.latitude }}

                </div>
                <div id="longitude">
                    <label id="long_label" class="copy" for="{{ form.longitude.auto_id }}">longitude</label>
                    {{ form.longitude }}
                </div>
            </div>


            <div class="left-side">
                    <p class="copy small-heading">name</p>
                    {{ form.name}}
                    <p class="copy small-heading">address or latitude/longitude</p>
                    {{ form.address }}
                    {{ form.city_and_state }}
                    {{ form.zip }}
            </div>
{#                    <p class="copy">What is it?</p>#}
{##}
{#                    <input type="hidden" value="{{ form.what_kind.value }}"#}
{#                           id="{{ form.what_kind.auto_id }}" name="{{ form.what_kind.name }}" />#}
{##}
{#                    <ul id="{{ form.what_kind.auto_id }}_choicefield">#}
{#                        {% for choice in form.what_kind.field.choices %}#}
{#                            <li {% if forloop.counter0 == 4 %}class="second"{% endif %}>#}
{#                                {% with maki=makis|getdict:choice.1 %}#}
{#                                    <a href="#"#}
{#                                       data-value="{{ choice.0 }}"#}
{#                                       class="{% if form.what_kind.value == choice.0|stringformat:'s' %}selected{% endif %} maki-icon {{ maki }}">#}
{##}
{#                                    </a>#}
{#                                {% endwith %}#}
{#                            </li>#}
{#                        {% endfor %}#}
{#                    </ul>#}


                    <p class="copy clr small-heading">about</p>
                    {{ form.about|add_class:"about-text" }}
                    <p class="copy clr small-heading">explore description: (136 characters max)</p>
                    {{ form.sherlock_description|add_class:"about-text"|attr:"maxlength:136" }}
                <div class="pos-rel">
{#                    <ul class="save-edit-list">#}
{#                        <li>#}
{#                            <a class="submit-type" href="#">edit</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a class="submit-type" href="#">save</a>#}
{#                        </li>#}
{#                    </ul>#}

                </div>

{#                    <p class="copy small-heading">news</p>#}
{#            <div class="news pos-rel">#}
{#                <ul class="save-edit-list">#}
{#                    <li>#}
{#                        <a class="submit-type" href="#">edit</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a class="submit-type" href="#">save</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#                    <div id="add-news-image">#}
{##}
{#                    </div>#}
{#                    {{ form.news|add_class:"news-text" }}#}

{#            <p class="copy small-heading">news</p>#}
{#                <a href="{{ location.get_list_news_url }}" class="blue s-button">List News</a>#}
{#                <a href="{{ location.get_add_news_url }}" class="blue s-button">Add News</a>#}

                    <p class="copy small-heading">pictures</p>
                    {% for picture in form.pictures %}
                        <div class="picture">

                        </div>
                    {% endfor %}
{#                    <div class="pictures">#}
{#                        #}
{#                        {{ form.pic1 }}#}
{#                        {{ form.pic2 }}#}
{#                        {{ form.pic3 }}#}
{#                        {{ form.pic4 }}#}
{##}
{#                    </div>#}

                    {% include "location/common/pictures-form.html" %}

                    <div style="clear:both;"></div>

                    {% if update %}
                        <input type="submit" class="admin-submit submit" value="update location"/>
                    {% else %}
                    <input type="submit" class="admin-submit submit" value="create location"/>
                    {% endif %}
        </form>
    </div>
{% endblock %}

{% block footerscripts %}

    <script type="text/javascript">
        window.start_lng = {{ coords.0 }};
        window.start_lat = {{ coords.1 }};
        window.start_zoom = 15;

    </script>

    <script src='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.js'></script>
{#    <script src='{{ STATIC_URL }}js/leaflet/leaflet.draw.js'></script>#}
    <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>

    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-mapbox.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-feature.js"></script>

    {% if organization %}
        <script type="text/javascript">
            var neighborhoods = neighborhoods || {};

            $(document).ready(function() {


                $.ajax({
                    url: "/api/v1/organizations/.json?org={{ organization.id }}",
                    dataType: "json",
                    success: function(d) {

                        var center = d.features[0].center.geometry.coordinates;

{#                        TB.Map.get_map().setView([center[1], center[0]], 15);#}
{#                        var hoods = L.geoJson(d,{#}
{#                            style: function (feature) {#}
{#                                return {stroke: false, fill: true};#}
{#                            },#}
{#                            onEachFeature: function (feature, layer) {#}
{#                                neighborhoods[feature.id] = {layer: layer,#}
{#                                    feature: feature};#}
{#                            }#}
{#                        }).addTo(map);#}

{#                        map.fitBounds(neighborhoods[{{ organization.id }}].layer);#}
{#                        hoods.eachLayer(function(e) {#}
{#                            var marker = e;#}
{#                        });#}
                    }
                });

                {% if form.latitude.value and form.longitude.value %}
                    L.marker([{{ form.latitude.value }}, {{ form.longitude.value }}], {
                        icon: L.mapbox.marker.icon({
                            'marker-size': 'large',
{#                            'marker-symbol': 'circle',#}
                            'marker-color': '#fa0'
                        })
                    }).addTo(TB.Map.featureGroup);
                {% endif %}
            });

            $(document).ready(function() {
                $('#id_sherlock_description').keyup(function() {
                    var content = $('#id_sherlock_description').html();
                    var extra = content.match(/.{19}(.*)/)[1];

                    $('#extra').html(extra);

                    var newContent = content.replace(extra, "<span class='highlight'>" + extra + "</span>");
                    $('#sample').html(newContent);
                });
            });
        </script>


    {% endif %}





        <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/jquery.file-input.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-fileinput.js"></script>

{% endblock %}

geo/location/templates/location/location_list.html
{% extends 'base.html' %}
{% load classnames %}
{% load widget_tweaks %}

{% block title %}
    Location List
{% endblock %}

{% block head %}

    <link rel="stylesheet" href="{{ STATIC_URL }}css/location/list.css" />
{% endblock %}

{% block bodyid %}location-list{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}

   {% for location in location_list %}
        <div class="idea-cap">
            {{ location.name }}
        </div>
    {% endfor %}

{% endblock %}

{% block footerscripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/jquery.file-input.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-fileinput.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-addidea.js"></script>
{% endblock %}