api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
# from geo.cities.views import CityViewset,CityTypeaheadViewset
from geo.places.views import PlacesViewset
from geo.location.views import LocationViewset
from geo.organization.views import OrganizationViewset
from tbnews.views import NewsItemViewset
import geo.location

router = routers.DefaultRouter()
# api = router.SimpleRouter()

router.register(r'locations', geo.location.views.LocationViewset, base_name="locations")
# router.register(r'cities', CityViewset)
router.register(r'places', PlacesViewset)
# router.register(r'cities-typeahead', CityTypeaheadViewset)
router.register(r'organizations', OrganizationViewset)

router.register(r'news', NewsItemViewset)

urlpatterns = patterns('',
                       # Examples:
                       url(r'^v1/', include(router.urls)),
                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

ideation/idea/urls.py
from django.conf.urls import patterns, include, url
from views import IdeaList, IdeaDetail, IdeaCreate

urlpatterns = patterns('ideation.idea.views',

   url(r'^flag/(?P<idea>[\w-]+)/?$', 'flag_idea', name='flag_idea'),
   url(r'^support/(?P<idea>[\w-]+)/?$', 'support_idea', name='support_idea'),
   url(r'^supporting/(?P<idea>[\w-]+)/?$', 'support_idea_from_detail', name='support_idea_from_detail'),

   url(r'^add/?$', 'addidea', name='addidea'),
   url(r'^add/(?P<place>[\w-]+)$', 'addidea', name='addidea'),
   url(r'^add/(?P<place>[\w-]+)/(?P<organization>[\w-]+)$', 'addidea', name='addidea'),
   url(r'^add/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/(?P<location>[\w-]+)$', 'addidea', name='addidea'),

   url(r'^list/?$', IdeaList.as_view(), name='idea_list'),
   url(r'^list/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/?$', IdeaList.as_view(), name='idea_list'),
   url(r'^list/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/(?P<location>[\w-]+)/?$', IdeaList.as_view(), name='idea_list'),

   url(r'^detail/(?P<place>[\w-]+)/(?P<idea>[\w-]+)/?$', IdeaDetail.as_view(), name='place_idea_detail'),
   url(r'^detail/(?P<place>[\w-]+)/(?P<organization>[\w-]+)/(?P<location>[\w-]+)/(?P<idea>[\w-]+)/?$', IdeaDetail.as_view(), name='idea_detail'),

   # url(r'^$', IdeaList.as_view(), name='idea_list'),
   # url(r'^(?P<state>\w+)/?$', IdeaList.as_view(), name='idea_list'),
   # url(r'^$', IdeaList.as_view(), name='idea_list'),
  )

ideation/idea/models.py
from django.db import models
from thoughtbubble.utils import path_and_rename
# from thoughtbubble.models import ThoughtbubbleUser
from django.conf import settings
import os
import hashlib
import datetime
from django.utils.timezone import now
from django.core.urlresolvers import reverse

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

from ideation.supportering.models import AbstractSupport

from thoughtbubble.utils import url_safe
from autoslug import AutoSlugField

from model_utils import Choices

import json as JSON

FOR_CHOICES = [
    ('morning', 'morning'),
    ('noon', 'noon'),
    ('night', 'night'),
    ('all day', 'all day'),
]


class IdeaType(models.Model):
    name = models.CharField(max_length=255)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ['ordering',]

    def __unicode__(self):
        return self.name



class Idea(models.Model):
    MOD_CHOICES = Choices('active','flagged','disabled')
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name',unique_with='object_id')

    description = models.TextField()

    what_kind = models.ForeignKey(IdeaType)
    what_for = models.CharField(max_length=20, choices=FOR_CHOICES)
    #where = models.ForeignKey(Location)

    # Getting Generic
    content_type = models.ForeignKey(ContentType, null=True)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey()


    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)

    date_created = models.DateTimeField(auto_now_add=True, default=now())
    date_modified = models.DateTimeField(auto_now=True, default=now())
    status = models.CharField(max_length=20, choices=MOD_CHOICES, default=MOD_CHOICES.active)

    # member = models.ForeignKey(ThoughtbubbleUser, related_name='member_idea_creator', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Idea, self).save(*args, **kwargs)

    def get_title(self):
        return "%s in %s for %s" % (self.name, self.content_object, self.what_for)

    def comment_count(self):
        return 0

    def get_parent_title(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return place.name
        else: # its a location
            location = self.content_object
            return location.organization.title

    def get_parent_label(self):
        if self.content_type.name == 'place':
            return "Place"
        else: # its a location
            return "Organization"

    def get_name(self):
        s = self.name
        indices = set([0])
        # s[0] = s[0].lower()
        return "".join(c.lower() if i in indices else c for i, c in enumerate(s))

    def get_parent_link(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return reverse('places_detail',args=[
                           url_safe(place.slug) ])
        else: # its a location
            location = self.content_object
            return reverse('organization_detail',args=[
                         url_safe(location.organization.place.slug),
                         url_safe(location.organization.slug),
                          #  url_safe(location.slug)
            ])


    def support_count(self):
        return IdeaSupport.objects.filter(idea=self).count()

    def get_days_since_added(self):
        d = now() - self.date_created
        return d.days

    def get_add_to_location_url(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return reverse('addidea',args=[
                url_safe(place.slug) ])
        else: # its a location
            location = self.content_object
            return reverse('addidea',args=[
                url_safe(location.organization.place.slug),
                url_safe(location.organization.slug),
                url_safe(location.slug),
                #  url_safe(location.slug)
            ])


    # TODO: Make these use place and location!
    def get_flag_url(self):
        return reverse('flag_idea',args=[url_safe(self.slug)])

    # TODO: Make these use place and location!
    def get_support_url(self):
        # if self.content_type.name == 'neighborhood':
        #     neighborhood = self.content_object
        # else: # its a location
        #     neighborhood = self.content_object.organization.neighborhood

        return reverse('support_idea',args=[url_safe(self.slug)])

    def get_absolute_url(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return reverse('place_idea_detail', args=[
                url_safe(place.slug),
                url_safe(self.slug)])
        else: # its a location
            location = self.content_object
            return reverse('idea_detail', args=[
                                            url_safe(location.organization.place.slug),
                                            url_safe(location.organization.slug),
                                            url_safe(location.slug),
                                            url_safe(self.slug)])


    def get_idea_location_name(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return place.name
        else: # its a location
            location = self.content_object
            return location.name

    def get_longitude(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return place.get_center()['coordinates'][0]

        else: # its a location
            location = self.content_object
            return location.longitude

    def get_latitude(self):
        if self.content_type.name == 'place':
            place = self.content_object
            return place.get_center()['coordinates'][1]

        else: # its a location
            location = self.content_object
            return location.latitude


    def get_wants(self):
        who_wants = "I want"
        if self.support_count() > 1:
                who_wants = "We want"
        return who_wants

    def get_fb_sharing(self):
        who_wants = "I want"
        if self.support_count() > 1:
            who_wants = "We want"
        return {
            'share_copy': "Support my idea at thoughtbubble.us!",
            'share_image': 'http://thoughtbubble.us/static/images/TB_socialicon.png',
            'share_caption': 'thoughtbubble.us',
            'share_name': "%s %s in %s" % (who_wants, self.name, self.get_idea_location_name()),
            'share_link': 'http://thoughtbubble.us' + self.get_absolute_url(),
            }

    def get_linkedin_sharing(self):
        who_wants = "I want"
        if self.support_count() > 1:
            who_wants = "We want"
        return {
            'summary': "%s %s in %s. Let's make this happen!" % (who_wants, self.name, self.get_idea_location_name()),
            'title': "%s %s in %s" % (who_wants, self.name, self.get_idea_location_name()),
            'share_link': 'http://thoughtbubble.us' + self.get_absolute_url(),
            }

    def get_twit_sharing(self):
        who_wants = "I want"
        if self.support_count() > 1:
            who_wants = "We want"
        return {
            'text': "%s %s in %s. Let's make this happen! %s" % (who_wants, self.name, self.get_idea_location_name(), 'http://thoughtbubble.us' + self.get_absolute_url())
        }

    def get_properties(self):
        properties = {}
        properties['title'] = self.name
        # properties['marker-size'] = 'medium'
        # properties['marker-color'] = '#f0a'
        # properties['marker-symbol'] = self.what_kind.maki_class if self.what_kind else 'Z'
        properties['link'] = self.get_absolute_url()

        properties['icon'] = {
            "iconUrl": "/static/images/large-featured-location.png",
            "iconSize": [47, 60],
            "iconAnchor": [30, 44],
            "popupAnchor": [0, -25]
        }

        # properties['icon'] = {
        #     "iconUrl": "http://placekitten.com/50/50",
        #     "iconSize": [50, 50], # size of the icon
        #     "iconAnchor": [25, 25], # point of the icon which will correspond to marker's location
        #      "popupAnchor": [0, -25]  # point from which the popup should open relative to the iconAnchor
        # }
        return properties

    def get_properties_json(self):
        return JSON.dumps(self.get_properties())

class IdeaSupport(AbstractSupport):
    idea = models.ForeignKey(Idea)


class IdeaImage(models.Model):
    idea = models.ForeignKey(Idea)
    img = models.ImageField(upload_to=path_and_rename('ideas','img'))
    name = models.CharField(max_length=255, blank=True, null=True)
    ordering = models.IntegerField(default=0)
    active = models.BooleanField(default=False)


def __unicode__(self):
        if self.name:
            return self.name
        else:
            return 'Img'


class IdeaLink(models.Model):
    idea = models.ForeignKey(Idea)
    url = models.CharField(max_length=1024)
    name = models.CharField(max_length=255, blank=True, null=True)

    def __unicode__(self):
        return self.url

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.url
        return super(IdeaLink, self).save(*args, **kwargs)

ideation/idea/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from models import *
from thoughtbubble.widgets import FilePicker
from geo.location.models import Location
from geo.places.models import Place


FOR_CHOICES_AND_EMPTY = [('when','when')] + FOR_CHOICES
REFINE_CHOICES = [('refine','refine'), ('recent','recent'), ('support','most supported')]
# <select name="order" id="order">
# <option value="">refine</option>
# <option value="recent" {% if ordering == "recent" %}selected{% endif %}>Recent</option>
# <option value="support" {% if ordering == "support" %}selected{% endif %}>Most Supported</option>
# </select>

class AddIdeaForm(forms.Form):
    name = forms.CharField(max_length=50,
                            error_messages={'required':'A name is required.'},
                            widget=forms.TextInput(attrs={'placeholder': 'title'}),)

    description = forms.CharField(widget=forms.Textarea(),
                                  error_messages={'required':'A description is required.'})

    what_kind = forms.ModelChoiceField(queryset=IdeaType.objects.all(),
                                       empty_label='',
                                       error_messages={'required':'Tell us what kind of idea this is.'})

    content_object = forms.ModelChoiceField(queryset=Location.objects.all().order_by('name'),
                                   empty_label='',
                                    error_messages={'required':'You must tell where it is.'}, required=False)

    content_object_place = forms.ModelChoiceField(queryset=Place.objects.all(),
                                            empty_label='',
                                            error_messages={'required':'You must tell where it is.'}, required=False)

    what_for = forms.ChoiceField(choices=FOR_CHOICES_AND_EMPTY,
                                 error_messages={'required':'Please specify what this is for.'},
                                 widget=forms.Select())

    links = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'link examples'}),required=False)

    pic1 = forms.ImageField(widget=FilePicker, required=False)
    pic2 = forms.ImageField(widget=FilePicker, required=False)
    pic3 = forms.ImageField(widget=FilePicker, required=False)
    pic4 = forms.ImageField(widget=FilePicker, required=False)

    def clean(self, *args, **kwargs):
        cleaned_data = super(AddIdeaForm, self).clean(*args, **kwargs)
        cleaned_data = dict(cleaned_data.items() + self.files.items())
        return cleaned_data

    def is_valid(self, *args, **kwargs):
        t = super(AddIdeaForm, self).is_valid(*args, **kwargs)
        return t



    # def clean(self, *args, **kwargs):
    #     cleaned_data = super(AddIdeaNeighborhoodForm, self).clean(*args, **kwargs)
    #     cleaned_data = dict(cleaned_data.items() + self.files.items())
    #     return cleaned_data



class FilterForm(forms.Form):
    order = forms.ChoiceField(choices=REFINE_CHOICES, required=False)
    # org = forms.IntegerField(widget=forms.HiddenInput(), initial=0, required=False)
    where_place = forms.ModelChoiceField(queryset=Place.objects.none(), empty_label='where', required=False)
    where_location = forms.ModelChoiceField(queryset=Location.objects.none(), empty_label='where', required=False)
    when = forms.ChoiceField(choices=FOR_CHOICES_AND_EMPTY, required=False)
    what = forms.ModelChoiceField(queryset=IdeaType.objects.all(), empty_label='what', required=False)

    def is_valid(self):
        super(FilterForm, self).is_valid()
        return True

ideation/idea/templates/idea/idea_detail.html
{% extends 'base.html' %}
{% load classnames %}
{% load widget_tweaks %}
{% load threadedcomments_tags %}
{% load ideacountables %}
{% load avatar_tags %}
{% load thumbnail %}

{% block title %}
    Idea List
{% endblock %}

{% block head %}
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.css' rel='stylesheet' />
    <!--[if lte IE 8]>
    <link href='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.ie.css' rel='stylesheet' />
  <![endif]-->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/idea/detail.css" />
{% endblock %}

{% block bodyid %}idea-detail{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}
    <div id="idea-wrapper">

            <div id="support-this">
                <a class="supporting login-required orange {% if idea|is_supported_by_user:user %}activated{% endif %}" data-id="{{ idea.id }}" href="{{ idea.get_support_url }}"><span class="unsupported"><i></i>support</span><span class="supported">supported</span></a>
                <a class="dislike blue" href="#">dislike</a>
                {% with fb=idea.get_fb_sharing twit=idea.get_twit_sharing linkedin=idea.get_linkedin_sharing %}
                    {% include "widgets/sharing.html" %}
                {% endwith %}
            </div>


        <span class="support-number"><i class="support-star-orange"></i>{{ idea.support_count }}</span> support this
        <a class="flag blue" href="{{ idea.get_flag_url }}"><img src="{{ STATIC_URL }}images/flag.png" alt=""/></a>
        <div id="spacer">
            <div class="clr"></div>
        </div>
        <div id="idea-details">
            <p>{{ idea.get_parent_label }}: <br/><a href="{{idea.get_parent_link }}">{{ idea.get_parent_title }}</a></p>
            <p>Location: <br/><b>{{ idea.content_object.name }}</b></p>
            <p>Type: <br/><b>{{ idea.what_kind }}</b></p>
            <p>When: <br/><b>{{ idea.what_for }}</b></p>
            <p>Idea by: <br/>{% avatar idea.user 25 %}<b>{{ idea.user.username }}</b></p>
        </div>
        <div class="r">{{ idea.get_wants }} <b>{{ idea.get_name }}</b></div>
        <div class="r">I imagine something like this:</div>
        <div id="idea-description">{{ idea.description|linebreaks }}</div>
        <div id="links" class="r">Links:
            {% for link in idea.idealink_set.all %}
                <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </div>

        <div id="images">
            {% for picture in pictures %}
                <a class="image-popup-no-margins" href="{{ picture.img.url }}">
                    <img src="{% thumbnail picture.img 80x80 %}" alt=""/>
                </a>
            {% endfor %}
        </div>
        <div style="clear:both;"></div>
        <div id="map"></div>

{#    Comments #}
        <div class="comments_wrapper" id="comments">
            {% render_comment_list for idea %}

            <div id="wrap_write_comment">
                {% if user.is_authenticated %}
                    {% render_comment_form for idea %}
                {% else %}
                    <a href="#submit" class="orange buttonize logintocomment login-required">login to comment</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block footerscripts %}
    <script src='//api.tiles.mapbox.com/mapbox.js/v2.0.1/mapbox.js'></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-mapbox.js"></script>
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-location.js"></script>#}
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/jquery.file-input.js"></script>#}
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-listidea.js"></script>


{#    Comments javascript #}
    <script type="text/javascript">

        function show_reply_form(event) {
            var $this = $(this);
            var comment_id = $this.data('comment-id');

            $('#id_parent').val(comment_id);
            $('#form-comment').insertAfter($this.closest('.comment'));
            $('.submit_comment').on('click', function(e){
                e.preventDefault();
                $(e.target).parent().submit();
            });
        };

        function cancel_reply_form(event) {
            $('#id_comment').val('');
            $('#id_parent').val('');
            $('#form-comment').appendTo($('#wrap_write_comment'));
        }

        $.fn.ready(function() {
            $('.comment_reply_link').click(show_reply_form);
            $('#cancel_reply').click(cancel_reply_form);
            $('.submit_comment').on('click', function(e){
                e.preventDefault();
                $(e.target).parent().submit();
            });
        });


        $('.comment_support').on('click', function(e) {
            e.preventDefault();
            $target = $(e.target);
            while (!$target.attr('href'))
                $target = $target.parent();

            $.ajax({
                url: $target.attr('href'),
                success: function(data) {
                    if (data.status == 'removed') {
                        $target.removeClass('activated');
                        $(document.body).trigger({type: 'comment:support:count', target: $target, count: data.count});
                    } else if (data.status == 'added') {
                        $target.addClass('activated');
                        $(document.body).trigger({type: 'comment:support:count', target: $target, count: data.count});
                    } else {

                    }
                }
            })
        });

        //Subscribe to events
    $(document.body).on('idea:support:count', function(e){
       $('.support-number').html(e.count);
    });

        $(document.body).on('comment:support:count', function(e){
            $('span',e.target).html(e.count);
        });



    </script>

    <script type="text/javascript">


        $(document).ready(function() {
            var map = TB.Map.get_map();
            TB.Map.featureLayer.on('layeradd', function(e) {

                var marker = e.layer,
                        feature = marker.feature;

                marker.setIcon(L.icon(feature.properties.icon));


                // http://leafletjs.com/reference.html#popup
{#                marker.bindPopup(popupContent,{#}
{#                    closeButton: false#}
{#                });#}
            });

            map.setView([{{ idea.get_latitude }},{{ idea.get_longitude }}],15);

            var map_features = {
                // this feature is in the GeoJSON format: see geojson.org
                // for the full specification
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    // coordinates here are in longitude, latitude order because
                    // x, y is the standard for GeoJSON and many formats
                    coordinates: [{{ idea.get_longitude }}, {{ idea.get_latitude }}]
                },
                properties: {{ idea.get_properties_json|safe }}
            }

            TB.Map.featureLayer.setGeoJSON(map_features);

        });



    </script>
{% endblock %}

ideation/idea/templates/idea/idea_filter.html
<form id="filtering" action="" method="get">
    <span id="sort_by">Sort by:</span><br/>

    {{ idea_filter.form.content_object }}
    {{ filterform.order }}
    {% if filterform.fields.where_location.queryset %}
        {{ filterform.where_location }}
    {% else %}
{#        {{ filterform.where_place }}#}
        <select id="id_where_place" name="where_place">

            <option value="" {% if not request.GET.where_place %}selected="selected"{% endif %}>where</option>
            {% for field in filterform.fields.where_place.queryset %}
                <option value="{{ field.pk }}" {% if request.GET.where_place|add:0 == field.pk %}selected="selected"{% endif %}>{{ field }} ({{ field.get_number_ideas }})</option>
             {% endfor %}
        </select>
    {% endif %}
    {{ filterform.when }}
    {{ filterform.what }}
{#    {{ filterform.org }}#}
</form>
<script type="text/javascript">
    $('#id_order').chosen({disable_search_threshold: 10, width:"100px"}).change( function(e) {
        $(e.target).parents('form').submit();
    });

    $('#id_where_place').chosen({disable_search_threshold: 10, width:"240px"}).change( function(e) {
        $(e.target).parents('form').submit();
    });

    $('#id_where_location').chosen({disable_search_threshold: 10, width:"240px"}).change( function(e) {
        $(e.target).parents('form').submit();
    });

    $('#id_when').chosen({disable_search_threshold: 10, width:"80px"}).change( function(e) {
        $(e.target).parents('form').submit();
    });

    $('#id_what').chosen({disable_search_threshold: 10, width:"130px"}).change( function(e) {
        $(e.target).parents('form').submit();
    });
</script>
{#{% for obj in filter %}#}
{#    {{ obj.name }} <br/>#}
{#{% endfor %}#}

ideation/idea/templates/idea/idea_for_list.html
{% load threadedcomments_tags %}
{% load ideacountables %}
<div class="idea-cap">
    <div class="left-idea-cap">
{#        <a href="{{ idea.get_absolute_url }}"><p>{{ idea.name }} in {{ idea.content_object.name }} for {{ idea.what_for }}</p></a>#}

        <ul class="idea-details-list">
            <li>{{ idea.content_object.name }} </li>
            <li>{{ idea.what_kind }}</li>
        </ul>


        <a href="{{ idea.get_absolute_url }}"><p>{% if idea.support_count %}{{ idea.support_count|pluralize:"I,We" }}{% else %}I{% endif %} want {{ idea.get_name }}</p></a>


        <ul class="right-idea-cap">
            <li><span class="emphasis support-star">{{ idea.support_count }}</span> supporters</li>
            <li><span class="emphasis comments-bubble">{% get_comment_count for idea as comment_count %} {{ comment_count }}</span> comments</li>
            <li>added {{ idea.get_days_since_added }} days ago</li>
        </ul>

        <div class="idea-interactions">
            <a class="supporting login-required orange {% if idea|is_supported_by_user:user %}activated{% endif %}" data-id="{{ idea.id }}" href="{{ idea.get_support_url }}"><span class="unsupported"><i></i>support</span><span class="supported">supported</span></a>
            <a class="commenting orange" data-id="{{ idea.id }}" href="{{ idea.get_absolute_url }}#comments">comment</a>
            {% with fb=idea.get_fb_sharing twit=idea.get_twit_sharing linkedin=idea.get_linkedin_sharing %}
                {% include "widgets/sharing.html" %}
            {% endwith %}
            <div class="clr"></div>
        </div>

    </div>

</div>

ideation/idea/templates/idea/idea_form.html
{% extends 'base.html' %}
{% load classnames %}
{% load widget_tweaks %}

{% block title %}
    Add an Idea
{% endblock %}

{% block head %}

    <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.min.css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/chosen.jquery.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/idea/add.css" />
{% endblock %}

{% block bodyid %}idea-form{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}

    <div id="form-wrapper">
        {{ form.errors }}
        <form enctype="multipart/form-data" action="{% url 'addidea' %}" method="POST">
            {% csrf_token %}
            <p class="copy want">I want</p>
            <div class="">{{ form.name}}</div>
            {{ form.what_kind|attr:"data-placeholder:It's a ..." }}
            {{ form.what_for|attr:"data-placeholder:For ..." }}
            {{ form.content_object|attr:"data-placeholder:It should be in ..." }}

            <div>
                <p class="copy additional">I imagine something like this:</p>
                <p class="copy additional">Similar to this:</p>
            </div>
            <div class="">
                <div id="pictures">
                    {{ form.pic1 }}
                    {{ form.pic2 }}
                    {{ form.pic3 }}
                    {{ form.pic4 }}
                </div>
                {{ form.description|add_class:"auto-hint"|attr:"title:type something here about your idea..." }}

            </div>

            <input type="submit" class="admin-submit submit" value="post"/>
        </form>
    </div>
{% endblock %}

{% block footerscripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/jquery.file-input.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-fileinput.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-addidea.js"></script>
{% endblock %}

ideation/idea/templates/idea/idea_list.html
{% extends 'base.html' %}
{% load classnames %}
{% load widget_tweaks %}

{% block title %}
    Idea List
{% endblock %}

{% block head %}

    <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/idea/list.css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/chosen.jquery.min.js"></script>
{% endblock %}

{% block bodyid %}idea-list{% endblock %}

{% block primarynav %}
{% endblock %}

{% block content %}

    {% include 'idea/idea_filter.html' %}

    {% for idea in ideas %}
        {% include 'idea/idea_for_list.html' %}
    {% endfor %}

{% endblock %}

{% block footerscripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/plugins/jquery.file-input.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-fileinput.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tb/tb-listidea.js"></script>
{% endblock %}